### ISSUE TITLE
Pull nemo-drivex and nemo-locatex in-house

### ISSUE THREAD

**Issue by grawk** [paypal/nemo-view#13]
Either, nemo-drivex/nemo-locatex should be dependencies of this module, else they should just be subsumed into it. Since most people don't use nemo-drivex or nemo-locatex in their test suites, there is no need to complicate their package.json and plugin configuration with them.

**Comment by grawk** [comment]
Amend this to say that "nemo-drivex" will be subsumed by "selenium-drivex" (https://github.com/grawk/selenium-drivex)

selenium-drivex is an agnostic version of convenience methods that can theoretically be used by any library utilizing selenium-webdriver.. not just nemo

**Comment by nikulkarni** [comment]
:+1:

**Comment by grawk** [comment]
WIP: https://github.com/grawk/nemo-view/tree/1.0-develop

**Comment by grawk** [comment]
done
