### ISSUE TITLE
add support for action sequence methods

### ISSUE THREAD

**Issue by nikulkarni** [paypal/nemo-view#23]
Like
- right click
- drag and drop
- double click etc

**Comment by grawk** [comment]
Are you implying new methods to the API of nemo-view? Or is there some issue with the current methods which are incompatible with the ActionSequence class?

**Comment by nikulkarni** [comment]
new methods

**Comment by grawk** [comment]
What would you propose? There are probably a few different approaches we could take but I haven't given it any thought yet.

**Comment by nikulkarni** [comment]
Actually I haven't given it a great deal of thought either. Just felt that we could have an abstraction added in nemo-view some how so that users don't have to know internals of selenium-webdriver. Wanted to open an issue so that it doesn't fall though. I'll let you know what I think

**Comment by nikulkarni** [comment]
@grawk This is what I think about actions support in nemo-view

     - Add support for actions for single elements in `star methods` like `locatorDoubleClick();`,  `locatorRightClick();`,  `locatorDragAndDrop();` etc. 
     - Add support in generic methods that involves interaction with more than one element like  `nemo.view._dragAndDrop(element1, element2);` and so on
     - May be In core nemo module we expose nemo.actions = nemo.driver.actions(); That way users can use nemo.actions for things that are not available in both generic and start methods? Like below. May be there is a better way to handle this use case here like accept a bunch of generic arguments and orchestrate a sequence based on that?

        ```
        nemo.actions.
                   keyDown(nemo.wd.Key.SHIFT).
                   click(nemoView.element1()).
                   click(element2).
                   dragAndDrop(nemoView.element1(), nemoView.element2()).
                   keyUp(nemo.wd.Key.SHIFT).
                   perform();
        ```

**Comment by nikulkarni** [comment]
@grawk what do you think? I can work on this if you are on board with this idea

**Comment by grawk** [comment]
Sorry I haven't looked at this sooner. I'm traveling tomorrow but will give it some thought and get back to you by EOD tomorrow

**Comment by grawk** [comment]
So it seems perhaps this would belong in another plugin called `nemo-actions` which would make sense to me. Nemo-view is mostly concerned with organizing, then selecting or waiting for WebElements. Any promise which resolves to a WebElement could be passed to an action command (in this theoretical plugin).

**Comment by nikulkarni** [comment]
Alright, I can get started on this.

**Comment by nikulkarni** [comment]
Since we decided this is not a nemo issue, closing this one
