### ISSUE TITLE
fix _find to only split on the first ':' that follows a locator type

### ISSUE THREAD

**Issue by jdeery** [paypal/nemo-view#24]
Currenty, the split that is performed withing nemo.view._find splits on all ':' Hence, if the locator itself contains ':' then part of the locator may be missed.

For example, with the locator ‘css:.businessBody a:nth-of-type(2)’, it looks like it will split after ‘a’ and leave out 'nth-of-type(2)'.

**Comment by grawk** [comment]
https://github.com/paypal/nemo-view/pull/21will fix this. will close this issue after merge and publish of that pr

**Comment by grawk** [comment]
Fix released as `v1.0.6`
