### ISSUE TITLE
*Wait is not sufficient for non-visible elements.

### ISSUE THREAD

**Issue by johnkchiu** [paypal/nemo-view#3]
In our application, maybe of the elements are dynamically made visible.  Using `*Wait()` is not sufficient, because it'll return before the element is visible.  It'll be useful to have a `*WaitForVisible()` that waits until the element is visible before returning.

(Note: If we're going to introduce helper functions like `*WaitAndClick()`, we should also introduct `*WaitForVisibleAndClick()`...)

**Comment by nikulkarni** [comment]
@johnkchiu `*Wait()` also take optional `timeout` and `msg` parameters. So if the default 5s timeout is not enough, you could pass a longer wait time as appropriate. Not sure if you noticed those optional params.

I agree that adding `*WaitForVisibleAndClick()` make sense. I will add that in my existing PR.

**Comment by grawk** [comment]
we should only add methods to nemo-view which provide significant convenience compared to the existing WebDriver statement(s) for accomplishing the same thing. In the case of *AndClick it is easier and less typing to just add .click() to a nemo-view method returning a WebElement.

**Comment by nikulkarni** [comment]
https://github.com/paypal/nemo-view/pull/2 Takes care of this.
