### ISSUE TITLE
At present don't have the ability to initialize locale at runtime. please add this feature.

### ISSUE THREAD

**Issue by vidyaravind** [paypal/nemo-view#31]

**Comment by grawk** [comment]
Thanks for filing this. I've got a WIP branch. Going to write unit tests then will file a PR tomorrow.

**Comment by grawk** [comment]
https://github.com/paypal/nemo-view/pull/32

**Comment by grawk** [comment]
This bug has been fixed with the close of PR #32 and released as `nemo-view@v1.2.0`
