### ISSUE TITLE
Support methods like in dom-testing-library

### ISSUE THREAD

**Issue by kentcdodds** [paypal/nemo-view#77]
The [`dom-testing-library`](https://github.com/kentcdodds/dom-testing-library) provides a collection of methods for selecting elements on a page in a way that encourages developers to write more maintainable code and tests.

Methods include:

- getByLabelText
- getByPlaceholderText
- getByText
- getByAltText
- getByTestId

I'm pretty inexperienced with selenium, but if there's some way to get access to the document to perform queries to get DOM nodes, then integrating this should be fairly straightforward. Even if you don't want to implement this directly into nemo-view, I'd be happy to create a `nemo-testing-library` people could use (similar libraries have been created for cypress, react, preact, vue, and soon ember). I just need some direction because as I said I'm pretty inexperienced with selenium... Thoughts?

**Comment by grawk** [comment]
Selenium provides access to DOM elements via the [`WebElement` Class](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebElement.html)

As far as I know, to access and script the DOM directly, you would need to use the [`executeScript`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebDriver.html#executeScript) method. From the docs, if a return value from the executed script is a DOM element, it will resolve into a `WebElement`.

**Comment by kentcdodds** [comment]
So presumably, we could run `getByLabelText` with something like:

```javascript
const body = await driver.findElement(By.tagName('body'));
const usernameInputDOMNode = getByLabelText(body, 'Username')
```

I have a feeling it wont be quite that simple :-(

**Comment by kentcdodds** [comment]
Makes sense. Thanks.

I'm probably not going to work on this myself, so I'll go ahead and close this issue. Thanks for your time Matt.
